# Generated by Django 3.2.4 on 2021-08-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('eid', models.CharField(blank=True, max_length=30, null=True)),
                ('skill1', models.CharField(blank=True, max_length=30, null=True)),
                ('skill2', models.CharField(blank=True, max_length=30, null=True)),
                ('skill3', models.CharField(blank=True, max_length=30, null=True)),
                ('skill4', models.CharField(blank=True, max_length=30, null=True)),
                ('skilll5', models.CharField(blank=True, max_length=30, null=True)),
                ('skillpercentage1', models.CharField(blank=True, max_length=5, null=True)),
                ('skillpercentage2', models.CharField(blank=True, max_length=5, null=True)),
                ('skillpercentage3', models.CharField(blank=True, max_length=5, null=True)),
                ('skillpercentage4', models.CharField(blank=True, max_length=5, null=True)),
                ('skillpercentage5', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('mid', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'manager',
            },
        ),
    ]
